import {t} from './i18n.js';
import * as T from 'three';
import {CALIBRATION_POINTS,rad} from './optics.js';
import {createEarth} from './earth.js';
import {RENDER_ASSUMPTIONS} from './device-data.js';
const CONTENT_POSE=RENDER_ASSUMPTIONS.virtualContentPose;
export function createContent(onChange=()=>{}){const contentScene=new T.Scene(),redraw=[];window.addEventListener('languagechange',()=>{redraw.forEach(fn=>fn());onChange();});let seed=7;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};function texture(draw,w=1024,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;redraw.push(()=>{draw(c.getContext('2d'),w,h);t.needsUpdate=true;});return t;}
// World-anchored virtual displays. Transparent target preserves overlay alpha.
const panels=new T.Group();contentScene.add(panels);const cinemaGroup=new T.Group(),workGroup=new T.Group(),blackGroup=new T.Group(),fovGroup=new T.Group(),visionGroup=new T.Group();panels.add(cinemaGroup,workGroup,blackGroup,fovGroup,visionGroup);
const earth=createEarth(onChange);earth.root.position.z=CONTENT_POSE.distance;panels.add(earth.root);
const film=texture((c,w,h)=>{let g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#061020');g.addColorStop(.6,'#143552');g.addColorStop(1,'#bc805e');c.fillStyle=g;c.fillRect(0,0,w,h);for(let i=0;i<100;i++){c.fillStyle='#c4d9e6';c.fillRect(random()*w,random()*h,2,2)}let x=w*.7,y=h*.44,r=h*.38;let planet=c.createRadialGradient(x-r*.4,y-r*.6,1,x,y,r);planet.addColorStop(0,'#f6dac1');planet.addColorStop(.5,'#bd8c79');planet.addColorStop(1,'#1c3044');c.fillStyle=planet;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.save();c.translate(x,y);c.rotate(-.35);c.strokeStyle='#c9c5b9bb';c.lineWidth=16;c.beginPath();c.ellipse(0,0,r*1.55,r*.22,0,0,Math.PI*2);c.stroke();c.restore();c.fillStyle='#e1edf6';c.font='500 74px sans-serif';c.fillText('O R B I T',90,h*.5);c.font='18px sans-serif';c.fillStyle='#a6bacb';c.fillText('A JOURNEY BEYOND THE KNOWN',95,h*.59);c.fillStyle='#b6d7ed';c.fillRect(90,h-58,w-180,2)},1280,720);
function display(w,h,tx,parent){let mesh=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tx,side:T.DoubleSide}));parent.add(mesh);return mesh}
display(CONTENT_POSE.cinemaWidth,CONTENT_POSE.cinemaHeight,film,cinemaGroup);
function documentTex(kind){return texture((c,w,h)=>{c.fillStyle='#0d182a';c.fillRect(0,0,w,h);c.fillStyle='#21334d';c.fillRect(0,0,w,45);c.fillStyle='#a7c1de';c.font='18px sans-serif';c.fillText(kind==='main'?t('STUDIO / 项目概览'):kind==='notes'?t('NOTES / 灵感收集'):t('FOCUS / 专注'),22,30);c.fillStyle='#e2eefa';c.font='bold 34px sans-serif';c.fillText(kind==='main'?t('让想法拥有空间'):kind==='notes'?t('下一个好点子'):'09:41',28,118);if(kind==='main'){c.fillStyle='#8da7c1';c.font='16px sans-serif';c.fillText('WEEK 04 · CREATIVE EXPLORATION',28,154);for(let i=0;i<9;i++){c.fillStyle=i>5?'#b5dacf':'#659bbd';let hh=60+((i*53)%145);c.fillRect(30+i*48,h-40-hh,27,hh)}}else for(let i=0;i<7;i++){c.fillStyle=i===0?'#94ccb9':'#657c97';c.fillRect(30,180+i*28,w*(i%2?.63:.75),i===0?8:4)}},512,430)}
const mainPanel=display(1.5,1.26,documentTex('main'),workGroup);for(let i of [-1,1]){let p=display(1.08,1.1,documentTex(i<0?'notes':'focus'),workGroup);p.position.set(i*1.35,-.02,.17);p.rotation.y=-i*.19}
const black=texture((c,w,h)=>{c.fillStyle='#000';c.fillRect(0,0,w,h);c.strokeStyle='#aadecb';c.lineWidth=5;c.strokeRect(3,3,w-6,h-6);c.fillStyle='#e1efef';c.textAlign='center';c.font='38px sans-serif';c.fillText(t('这里的像素是黑色'),w/2,h*.32);c.font='20px sans-serif';c.fillStyle='#a6bbc7';c.fillText(t('观察黑色区域后面的房间'),w/2,h*.49);['#000','#202020','#555','#aaa','#fff'].forEach((color,i)=>{c.fillStyle=color;c.fillRect(w*.18+i*w*.135,h*.67,w*.105,h*.16)})},900,520);display(2.4,1.387,black,blackGroup);

const visionTarget=texture((c,w,h)=>{c.fillStyle='#090f16';c.fillRect(0,0,w,h);c.fillStyle='#e8f1ed';c.font='24px sans-serif';c.fillText(t('FOCUS / 观察线条、文字与点光'),48,50);const x=210,y=240;for(let i=0;i<24;i++){const a=i*Math.PI/12;c.strokeStyle='#f5f6ed';c.lineWidth=3;c.beginPath();c.moveTo(x+30*Math.cos(a),y+30*Math.sin(a));c.lineTo(x+135*Math.cos(a),y+135*Math.sin(a));c.stroke();}c.font='64px sans-serif';c.fillText('E F P T O Z',420,180);c.font='42px sans-serif';c.fillText(t('P E C F D   空间里的文字'),420,258);c.font='27px sans-serif';c.fillText(t('同一视角 · 比较矫正前后'),420,319);for(let i=0;i<5;i++){c.fillStyle='#fffbe8';c.beginPath();c.arc(470+i*106,410,3+i*.8,0,Math.PI*2);c.fill();}c.fillStyle='#78938a';c.font='20px sans-serif';c.fillText(t('VISUAL DEMO · 不是视力检查'),48,h-36);},1100,520);display(2.6,1.23,visionTarget,visionGroup);
const testTexture=texture((c,w,h)=>{c.clearRect(0,0,w,h);c.fillStyle='rgba(38,66,76,.08)';c.fillRect(0,0,w,h);const fx=w/(2*Math.tan(50*Math.PI/180)),fy=h/(2*Math.tan(40*Math.PI/180));c.textAlign='center';c.textBaseline='middle';for(let deg=-40;deg<=40;deg+=10){let x=w/2+fx*Math.tan(deg*Math.PI/180);c.strokeStyle=deg===0?'#e8f2f4':'#92b6b980';c.lineWidth=deg===0?3:1.5;c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();if(deg)c.fillStyle='#c7dedf',c.font='35px sans-serif',c.fillText(deg+'°',x,h/2-25);}for(let deg=-30;deg<=30;deg+=10){let y=h/2-fy*Math.tan(deg*Math.PI/180);c.strokeStyle=deg===0?'#e8f2f4':'#92b6b980';c.lineWidth=deg===0?3:1.5;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();if(deg)c.fillStyle='#c7dedf',c.font='35px sans-serif',c.fillText(deg+'°',w/2+35,y);}c.strokeStyle='#e3cfa5';c.lineWidth=4;c.beginPath();c.arc(w/2,h/2,fx*Math.tan(15*Math.PI/180),0,Math.PI*2);c.stroke();c.font='29px sans-serif';c.fillStyle='#dfcba3';c.fillText('30°',w/2,h/2+fx*Math.tan(15*Math.PI/180)+30);for(const point of CALIBRATION_POINTS){const x=w/2+fx*Math.tan(point.h*rad),y=h/2-fy*Math.tan(point.v*rad);c.fillStyle=point.color;c.beginPath();c.arc(x,y,30,0,Math.PI*2);c.fill();c.fillStyle='#12232a';c.font='bold 43px sans-serif';c.fillText(point.id,x,y+1);}},1536,1082);
const gridMat=new T.MeshBasicMaterial({map:testTexture,transparent:true,side:T.DoubleSide,depthWrite:false});const grid=new T.Mesh(new T.PlaneGeometry(2*CONTENT_POSE.distance*Math.tan(50*Math.PI/180),2*CONTENT_POSE.distance*Math.tan(40*Math.PI/180)),gridMat);fovGroup.add(grid);
return {scene:contentScene,setEarth:earth.setView,getSnapshot(){return {earth:earth.getSnapshot(),position:panels.position.toArray(),quaternion:panels.quaternion.toArray(),scale:panels.scale.toArray(),cinemaGeometry:cinemaGroup.children[0].geometry.parameters};},getMarkers(){return CALIBRATION_POINTS.map(p=>({id:p.id,position:new T.Vector3(CONTENT_POSE.distance*Math.tan(p.h*rad),CONTENT_POSE.distance*Math.tan(p.v*rad),0).applyQuaternion(panels.quaternion).add(panels.position)}));},anchor(position,quaternion=new T.Quaternion()){panels.quaternion.copy(quaternion);panels.position.copy(position).add(new T.Vector3(0,0,-CONTENT_POSE.distance).applyQuaternion(quaternion));},setContent(kind){earth.root.visible=kind==='earth';cinemaGroup.visible=kind==='cinema';workGroup.visible=kind==='work';blackGroup.visible=kind==='black';fovGroup.visible=kind==='fov';visionGroup.visible=kind==='vision';}};
}
